spring.datasource.url=jdbc:postgresql://localhost:5432/tour_agency
spring.datasource.username=postgres
spring.datasource.password=19311
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
